imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    # ...
    dbal:
        host:     127.0.0.1
        dbname:   '%database_test_name%'
        user:     'database_test_user%'
        password: '%database_test_password%'

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
