gc_user:
    resource: "@GCUserBundle/Resources/config/routing.yml"
    prefix:   /

gc_reservation:
    resource: "@GCReservationBundle/Resources/config/routing.yml"
    prefix:   /

gc_evenement:
    resource: "@GCEvenementBundle/Resources/config/routing.yml"
    prefix:   /

gc_home:
    resource: "@GCHomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
