app_magasin:
    resource: "@AppBundle/Controller/MagasinController.php"
    type:     annotation

app_transaction:
    resource: "@AppBundle/Controller/TransactionController.php"
    type:     annotation

app_mode_de_paiement:
    resource: "@AppBundle/Controller/ModeDePaiementController.php"
    type:     annotation

app_service:
    resource: "@AppBundle/Controller/ServiceController.php"
    type:     annotation

app_produit:
    resource: "@AppBundle/Controller/ProduitController.php"
    type:     annotation

app_salle:
    resource: "@AppBundle/Controller/SalleController.php"
    type:     annotation

app_annonce:
    resource: "@AppBundle/Controller/AnnonceController.php"
    type:     annotation

app_facture:
    resource: "@AppBundle/Controller/FactureController.php"
    type:     annotation

app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app_reservation:
    resource: "@AppBundle/Controller/ReservationController.php"
    type:     annotation

app_place:
    resource: "@AppBundle/Controller/PlaceController.php"
    type:     annotation

gc_user:
    resource: "@GCUserBundle/Resources/config/routing.yml"
    prefix:   /

gc_reservation:
    resource: "@GCReservationBundle/Resources/config/routing.yml"
    prefix:   /

gc_evenement:
    resource: "@GCEvenementBundle/Resources/config/routing.yml"
    prefix:   /

gc_home:
    resource: "@GCHomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"


#Tihs is routes for GustoCoffee Backoffice
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /backoffice


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /
