app_type_de_produit:
    resource: "@AppBundle/Controller/TypeDeProduitController.php"
    type:     annotation
    options:
        sitemap: true

app_ligne_facture:
    resource: "@AppBundle/Controller/LigneFactureController.php"
    type:     annotation
    options:
        sitemap: true

gc_user:
    resource: "@GCUserBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        sitemap: true

gc_reservation:
    resource: "@GCReservationBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        sitemap: true
gc_evenement:
    resource: "@GCEvenementBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        sitemap: true
gc_home:
    resource: "@GCHomeBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        sitemap: true
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /
    options:
        sitemap: true
#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

api:
    resource: '@AppBundle/Resources/config/routing_api.yml'
    prefix: /api
    type: rest
    options: { i18n: false }
    defaults:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc
    options: { i18n: false }

facebook_login:
    path: /connect/check-facebook
    options: { i18n: false }

google_login:
    path: /connect/check-google
    options: { i18n: false }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    options: { i18n: false }

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect
    options: { i18n: false }

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect
    options: { i18n: false }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#Tihs is routes for GustoCoffee Backoffice
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /backoffice

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

fos_user_profile:
    resource: "@GCUserBundle/Resources/config/routing/profile.xml"
    prefix: /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

DpnXmlSitemapBundle:
    resource: "@DpnXmlSitemapBundle/Resources/config/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"