# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER # user front-end
        ROLE_GC_EMPLOYER: [ROLE_USER, ROLE_GC_EMPLOYER]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            form_login:
                provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: /reservation
        api:
            pattern: ^/api/

            #fos_oauth:                                  # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            logout:    true
            anonymous: true                           # Anonymous access is not allowed
            guard:
                authenticators:
                    - 'token_authenticator'
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #check_path: fos_user_security_login_check
                #login_path: fos_user_security_login
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: /%locale%/reservation

            logout:
                path: fos_user_security_logout
            anonymous: true

            oauth:
                resource_owners:
                    facebook:      "/connect/check-facebook"
                    google:        "/connect/check-google"
                login_path:        /connect
                use_forward:       false
                failure_path:      /connect

                oauth_user_provider:
#                    service: my.oauth_aware.user_provider.service
                    service: hwi_oauth.user.provider.fosub_bridge
#                    service: my.user_provider.service


        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login


    access_control:
        #- { path: ^/api/,  roles: [ROLE_USER] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/backoffice/, role: ROLE_ADMIN }
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }





        #- { path: ^/[^/]+/login$,     host: ^%domain_name%$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/[^/]+/register,   host: ^%domain_name%$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/[^/]+/resetting,  host: ^%domain_name%$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/[^/]+/admin/,     host: ^%domain_name%$,    role: ROLE_ADMIN }
        #- { path: ^/[^/]+/api,  role: [ IS_AUTHENTICATED_FULLY ] }
        # - { path: ^/[^/]+/,  host: ^%domain_name%$, role: IS_AUTHENTICATED_ANONYMOUSLY }

