easy_admin:
    entities:
        Commande:
            class: AppBundle\Entity\Commande
            #controller: AppBundle\Controller\Backoffice\CommandeController
            disabled_actions: ['delete']
            label: 'Les Commandes'
            form:
                fields: ['dateCommande', 'idDemandeProduit', 'idModePaiement', 'idPersonne']
            list:
                title: 'Les Commandes'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['dateCommande', 'idDemandeProduit', 'idModePaiement', 'idPersonne']