easy_admin:
    entities:
        Magasin:
            class: AppBundle\Entity\Magasin
            label: 'Les Magasins'
            form:
                fields: [{property: 'nomMagasin', type: 'text'}, 'adresse', {property: 'telephone', type: 'text'}]
            list:
                title: 'Les Magasins'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['nomMagasin', 'adresse', 'telephone']

        JoursOuvert:
            class: AppBundle\Entity\JoursOuvert
            label: 'Ouverture'
            form:
                fields: [{property: 'jours', type: 'text'}, { property: 'heureDebut', type: 'time'},  { property: 'heureFin' , type: 'time'}, 'titre', 'idmagasin']
            list:
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                title: 'Les jours d''ouvertures'
                fields: [{property: 'jours', type: text}, { property: 'heureDebut', type: 'time'}, { property: 'heureFin' , type: 'time'}, 'titre', 'idmagasin']
                sort: 'idouverture'
            edit:
                fields: ['jours', { property: 'heureDebut', type: 'time'}, { property: 'heureFin', type: 'time'}, 'titre', 'idmagasin']

        FermetureCafe:
          class: AppBundle\Entity\FermetureDuCafe
          label: 'Fermeture'
          form:
              fields: [{property: 'datedebut', type: 'date' }, { property: 'datefin', type: 'date' }, {property: 'titre', type: 'text' }, 'raison', 'jourFerie', 'idmagasin']
          list:
              title: 'Les jours de fermeture'
              fields: ['datedebut', 'datefin', 'titre', 'raison', 'jourFerie', 'idmagasin']

        Service:
            class: AppBundle\Entity\Service
            label: 'Les Services'
            form:
                fields: ['nomService', 'prixService', 'description', 'quantiteEnStock', 'statutService']
            list:
                title: 'Services'
                fields: ['nomService', 'prixService', 'description', 'quantiteEnStock', 'statutService']
        Place:
            class: AppBundle\Entity\Place
            label: 'Les Places'
            form:
                fields:
                    - { property: 'nomPlace', type: 'text'}
                    - { property: 'statutPlace', type: 'text'}
                    - { property: 'idsalle'}
            list:
                title: 'Places'
                fields: ['nomPlace', 'statutPlace', 'idsalle']

        ModeDePaiement:
            class: AppBundle\Entity\ModeDePaiement
            label: 'Modes de paiements'
            form:
                fields:
                    - { property: 'modePaiement', type: 'text', label: 'Mode de paiement' }
                    - 'description'

            list:
                title: 'Liste des modes de paiements disponible'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: [ {property: 'modePaiement', label: 'Mode de paiement' }, 'description' ]
            edit:
                fields: [ {property: 'modePaiement', label: 'Mode de paiement' }, 'description' ]

        Tva:
            class: AppBundle\Entity\Tva
            label: 'Tva FR'
            form:
                fields:
                    - { property: 'nom', type: 'text'}
                    - { property: 'valeur'}
                    - { property: 'multiplicate' }
            list:
                title: 'Tva FR'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'idtva', type: 'text'}
                    - { property: 'nom', type: 'text'}
                    - { property: 'valeur'}

        GrilleTarifaire:
            class: AppBundle\Entity\GrilleTarifaire
            label: 'Grille Tarifaire'
            form:
                fields:

                    - { property: 'nom', type: 'text'}
                    - { property: 'prix',   type: 'money', type_options: { currency: 'EUR' }, help: 'Prix en € TTC (exemple: 3.5 ou 5 sans le symbole €'}
                    - { property: 'duree', type: 'number', help: 'Heure pour un prix donnée (exemple: 1 sans le H, ou 2,5 pour deux heures et demies'}
                    - 'idmagasin'
            list:
                title: 'Grille Tarifaire FR'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - idgrilletarifaire
                    - { property: 'nom', type: 'text'}
                    - { property: 'prix', label: 'Prix en €' }
                    - { property: 'duree', type: 'text' }
                    - 'idmagasin'