easy_admin:
    entities:
        Magasin:
            class: AppBundle\Entity\Magasin
            label: 'Les Magasins'
            form:
                fields: ['nomMagasin', 'adresse']
            list:
                title: 'Les Magasins'
                fields: ['nomMagasin', 'adresse']

        JoursOuvert:
            class: AppBundle\Entity\JoursOuvert
            label: 'Ouverture'
            form:
                fields: ['jours', { property: 'heureDebut', type: 'time'},  { property: 'heureFin' , type: 'time'}, 'titre']
            list:
                title: 'Les jours d''ouverture'
                fields: ['jours', { property: 'heureDebut', type: 'time'}, { property: 'heureFin' , type: 'time'}, 'titre']
                sort: 'idouverture'
            edit:
                fields: ['jours', { property: 'heureDebut', type: 'time'}, { property: 'heureFin', type: 'time'}, 'titre']

        FermetureCafe:
          class: AppBundle\Entity\FermetureDuCafe
          label: 'Fermeture'
          form:
              fields: ['dateDebut', 'dateFin', 'heureDebut', 'heureFin', 'titre', 'raison', 'jourFerie']
          list:
              title: 'Les jours d''ouverture'
              fields: ['dateDebut', 'dateFin', 'heureDebut', 'heureFin', 'titre', 'raison', 'jourFerie']
        Service:
          class: AppBundle\Entity\Service
          label: 'Les Services'
          form:
              fields: ['nomService', 'prixService', 'description', 'quantiteEnStock', 'statutService']
          list:
              title: 'Services'
              fields: ['nomService', 'prixService', 'description', 'quantiteEnStock', 'statutService']
        Place:
          class: AppBundle\Entity\Place
          label: 'Les Places'
          form:
              fields:
                  - { property: 'nomPlace', type: 'text'}
                  - { property: 'statutPlace', type: 'text'}
                  - { property: 'idsalle'}
          list:
              title: 'Places'
              fields: ['nomPlace', 'statutPlace', 'idsalle']

        ModeDePaiement:
          class: AppBundle\Entity\ModeDePaiement
          label: 'Modes de paiements'
          form:
              fields:
                  - { property: 'modePaiement', type: 'text', label: 'Mode de paiement' }
                  - 'description'

          list:
              title: 'Liste des modes de paiements disponible'
              fields: [ {property: 'modePaiement', label: 'Mode de paiement' }, 'description' ]
          edit:
              fields: [ {property: 'modePaiement', label: 'Mode de paiement' }, 'description' ]
