easy_admin:
    entities:
        Personne:
            class: AppBundle\Entity\Personne
            label: 'Utilisateurs'
            form:
                fields: ['id', 'username', 'email', 'nom', 'prenom', 'motdepasse', 'enabled', 'lastLogin', 'statutpersonne', 'newsletter']
            list:
                title: 'Les Utilisateurs'
                fields: ['id', 'username', 'email', 'nom', 'prenom', 'enabled', 'lastLogin', 'statutpersonne', 'newsletter', { property: 'email', label: 'Contact Email' }]
            edit:
                - { property: 'username', icon: 'user' }
                - { property: 'email', css_class: 'input-large', type_options: { required: false } }
            new:
                - { property: 'username', icon: 'user' }
                - { property: 'email', css_class: 'input-large', type_options: { required: false } }