easy_admin:
    entities:
        Produit:
            class: AppBundle\Entity\Produit
            label: 'Les Produits'
            form:
                fields: [ {property: 'nomProduit', type: 'text'}, 'prixProduit', 'description', 'quantiteEnStock', 'statutProduit']
            list:
                title: 'Les Produits'