easy_admin:
    entities:
        Produit:
            class: AppBundle\Entity\Produit
            label: 'Les Produits'
            form:
                fields:
                    - { property: 'nomProduit', type: 'text'}
                    - { property: 'prixProduit', type: 'text'}
                    - { property: 'description', type: 'text'}
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'quantiteEnStock', type: 'text'}
                    - { property: 'statutProduit', type: 'text'}
            list:
                title: 'Listes des Produits'
                fields:
                    - { property: 'nomProduit', type: 'text'}
                    - { property: 'prixProduit', type: 'text'}
                    - { property: 'description', type: 'text'}
                    - { property: 'image', type: 'image', base_path: %app.path.products_images% }
                    - { property: 'quantiteEnStock', type: 'text'}
                    - { property: 'statutProduit', type: 'text'}

            show:
                title: 'Show des Produits'
                fields:
                    - { property: 'nomProduit', type: 'text'}
                    - { property: 'prixProduit', type: 'text'}
                    - { property: 'description', type: 'text'}
                    - { property: 'image', type: 'image', base_path: %app.path.products_images% }
                    - { property: 'quantiteEnStock', type: 'text'}
                    - { property: 'statutProduit', type: 'text'}
