easy_admin:
    entities:
        Salle:
          class: AppBundle\Entity\Salle
          label: 'Les Salles'
          form:
              fields:
                  - { property: 'nomSalle', type: 'text'}
                  - { property: 'capacityMax', type: 'text'}
                  - { property: 'imageFile', type: 'vich_image'}
                  - 'idmagasin'
          list:
              title: 'Listes des Salles'
              actions:
                  - { name: 'show', label: '', icon: 'search' }
                  - { name: 'edit', label: '', icon: 'edit' }
                  - { name: 'delete', label: '', icon: 'trash' }
              fields:
                  - 'idsalle'
                  - { property: 'nomSalle', sortable: true }
                  - { property: 'capacityMax', sortable: true }
                  - { property: 'image', type: 'image', base_path: %app.path.salles_images% }
                  - 'idmagasin'
              sort: ['idsalle', 'ASC']
          show:
              title: 'Détails de la salle'
              fields:
                  - 'nomSalle'
                  - 'capacityMax'
                  - { property: 'image', type: 'image', base_path: %app.path.salles_images% }
                  - 'idmagasin'
                  - 'createdAt'
                  - 'updateAt'