<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
    public function byFacture($personne)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.personnes = :personne')
                ->andWhere('u.valider = 1')
                ->andWhere('u.reference != 0')
                ->orderBy('u.idcommande', 'DESC')
                ->setParameter('personne', $personne);
        
        return $qb->getQuery()->getResult();
    }
    public function byLastFacture($personne)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.personnes = :personne')
            ->andWhere('u.valider = 1')
            ->andWhere('u.reference != 0')
            ->orderBy('u.idcommande', 'DESC')
            ->setMaxResults(3)
            ->setParameter('personne', $personne);

        return $qb->getQuery()->getResult();
    }

    public function byDateCommand($date)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.datecommande > :date')
                ->andWhere('u.valider = 1')
                ->orderBy('u.idcommande')
                ->setParameter('date', $date);
        
        return $qb->getQuery()->getResult();
    }

    public function amountByYear()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u.datecommande, u.commande')
            ->andWhere('u.valider = 1')
            ->orderBy('u.idcommande');

        return $qb->getQuery()->getResult();

    }
}
