<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacesRepository extends EntityRepository
{

    public function getAllPositions($idsalle){
        $qb = $this->createQueryBuilder('u')
            ->Select('u.position')
            ->where('u.idsalle = :idsalle')
            ->setParameter('idsalle', $idsalle)
            ->orderBy('u.position');

        return $qb->getQuery()->getResult();
    }

    public function getPlaceUnavailable(){
        $qb = $this->createQueryBuilder('u')
            ->Select('u.position')
            ->where('u.statutplace = indisponible');

        return $qb->getQuery()->getResult();
    }

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.idplace IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

    public function recherche($chaine)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.nom like :chaine')
                    ->andWhere('u.disponible = 1')
                    ->orderBy('u.idproduit')
                    ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }
}
