<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.idproduit IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
    
    public function byCategorie($categorie)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->andWhere('u.quantiteenstock > 0')
                    ->orderBy('u.idproduit');
        return $qb->getQuery()->getResult();
    }
    
    public function recherche($chaine)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.nomproduit like :chaine')
                    ->andWhere('u.quantiteenstock > 0')
                    ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }
}
