<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    public function byFacture($personne)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.personnes = :personne')
                ->andWhere('u.valider = 1')
                ->andWhere('u.reference != 0')
                ->orderBy('u.idcommande', 'DESC')
                ->setParameter('personne', $personne);
        
        return $qb->getQuery()->getResult();
    }

    public function byDatetransation($date)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.datetransaction > :date')
                ->andWhere('u.valider = 1')
                ->setParameter('date', $date);
        
        return $qb->getQuery()->getResult();
    }
}
