<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesRepository extends EntityRepository
{
    public function findCp($cp)
    {
        $query = $this->createQueryBuilder('v')
            ->where('v.villeCodePostal LIKE :cp')
            ->setParameter('cp', '%'.(string)$cp.'%')
            ->distinct(true);

        return $query->getQuery()->getResult();
    }

}
