<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Salle;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class FixtureSalle extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Salle::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Salle();
        $item1->setNomsalle("Salle A");
        $item1->setCapacitymax(4);
        $item1->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item1->setImage("groupPlace.jpg");
        $item1->setUpdatedAt(new \DateTime("2017-09-19 16:03:39"));
        $item1->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle1', $item1);
        $manager->persist($item1);

        $item2 = new Salle();
        $item2->setNomsalle("Salle B");
        $item2->setCapacitymax(4);
        $item2->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item2->setImage("groupPlace.jpg");
        $item2->setUpdatedAt(new \DateTime("2017-09-19 16:02:11"));
        $item2->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle2', $item2);
        $manager->persist($item2);

        $item3 = new Salle();
        $item3->setNomsalle("Salle C");
        $item3->setCapacitymax(4);
        $item3->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item3->setImage("groupPlace.jpg");
        $item3->setUpdatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $item3->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle3', $item3);
        $manager->persist($item3);

        $item4 = new Salle();
        $item4->setNomsalle("Open Space");
        $item4->setCapacitymax(150);
        $item4->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item4->setImage("individuelPlace.jpg");
        $item4->setUpdatedAt(new \DateTime("2017-09-19 16:06:02"));
        $item4->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle4', $item4);
        $manager->persist($item4);

        $item5 = new Salle();
        $item5->setNomsalle("Salle D");
        $item5->setCapacitymax(4);
        $item5->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item5->setImage("groupPlace.jpg");
        $item5->setUpdatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $item5->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle5', $item5);
        $manager->persist($item5);

        $item6 = new Salle();
        $item6->setNomsalle("Salle E");
        $item6->setCapacitymax(4);
        $item6->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item6->setImage("groupPlace.jpg");
        $item6->setUpdatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $item6->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle6', $item6);
        $manager->persist($item6);

        $item7 = new Salle();
        $item7->setNomsalle("Salle F");
        $item7->setCapacitymax(6);
        $item7->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item7->setImage("groupPlace.jpg");
        $item7->setUpdatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $item7->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle7', $item7);
        $manager->persist($item7);

        $item8 = new Salle();
        $item8->setNomsalle("Salle G");
        $item8->setCapacitymax(6);
        $item8->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item8->setImage("images.jpeg");
        $item8->setUpdatedAt(new \DateTime("2017-09-19 16:00:47"));
        $item8->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle8', $item8);
        $manager->persist($item8);

        $item9 = new Salle();
        $item9->setNomsalle("Salle H");
        $item9->setCapacitymax(6);
        $item9->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item9->setImage("groupPlace.jpg");
        $item9->setUpdatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $item9->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle9', $item9);
        $manager->persist($item9);

        $item10 = new Salle();
        $item10->setNomsalle("Salle I");
        $item10->setCapacitymax(6);
        $item10->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item10->setImage("images.jpeg");
        $item10->setUpdatedAt(new \DateTime("2017-09-19 16:01:17"));
        $item10->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle10', $item10);
        $manager->persist($item10);

        $item11 = new Salle();
        $item11->setNomsalle("Salle J");
        $item11->setCapacitymax(6);
        $item11->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item11->setImage("téléchargement.jpeg");
        $item11->setUpdatedAt(new \DateTime("2017-09-19 16:02:44"));
        $item11->setCreatedAt(new \DateTime("-0001-11-30 00:00:00"));
        $this->addReference('_reference_AppBundleEntitySalle11', $item11);
        $manager->persist($item11);

    
        $manager->flush();
    }

}
