<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Place;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadFixturePlace extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Place::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $line = 1;
        $car = 'A';
        $maxligne=12;
        $maxcolonne=10;
        for ($i = 1 ; $i <= $maxligne ; $i++){
            $col = 1;
            for ($j = 1 ; $j <= $maxcolonne ; $j++){
                if($j % 3 == 0  && $j != 1) {
                    ++$col;
                }
                // Ajout de place en bdd aux bonnes positions
                echo 'Nom place: '.$car.$col . "Position: ". $line."_". $col ."\n";
                $item1 = new Place();
                $item1->setNomplace($car.$col);
                $item1->setPosition($line."_".$col);
                $item1->setLigne($line);
                $item1->setColonne($col);
                $item1->setStatutplace("libre");

                $manager->persist($item1);
                $manager->flush();
                $col++;
            }
            if ($i % 3 == 0){
                $vide = '' ;
                for($v = 1 ; $v <= $maxcolonne ; $v++){
                    $vide .= '_';
                }
                $line++;
                $car++;
            }
            $car++;
            $line++;
        }

    }

}
