<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Place;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadFixturePlace extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {

        $manager->getClassMetadata(Place::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

//        $j = 1;
//        $c = 'A';
//        $p = 1;
//        for ($i = 1; $i <= 120; $i++) {
//            if ($j > 10) {
//                $c++;
//                $p++;
//                $j = 1;
//            }
//            echo $c . "" .$j . "  position: ". $p."_". $j ."\n";
//            $item1 = new Place();
//            $item1->setNomplace($c."".$j);
//            $item1->setPosition($p."_". $j);
//            $item1->setColonne($j);
//            $item1->setLigne($p);
//            $item1->setStatutplace("libre");
////            $item1->setIdsalle($this->getReference());
//           // $this->addReference('_reference_AppBundleEntityPlace'.$i, $item1);
//            $manager->persist($item1);
//            $manager->flush();
//
//            $j++;
//        }

        $line = 1;
        $car = 'A';
        $maxligne=12;
        $maxcolonne=10;
        for ($i = 1 ; $i <= $maxligne ; $i++){
            $row = '' ;
            $col = 1;
            for ($j = 1 ; $j <= $maxcolonne ; $j++){
                if($j % 3 == 0  && $j != 1) {
                    $row .= '_';
                    ++$col;
                }
                $row .= 'p';
                // Ajout de place en bdd aux bonnes positions
                echo 'Nom place: '.$car.$col . "Position: ". $line."_". $col ."\n";
                $item1 = new Place();
                $item1->setNomplace($car.$col);
                $item1->setPosition($line."_". $line);
                $item1->setLigne($line);
                $item1->setColonne($col);
                $item1->setStatutplace("libre");
//            $item1->setIdsalle($this->getReference());
                // $this->addReference('_reference_AppBundleEntityPlace'.$i, $item1);
                $manager->persist($item1);
                $manager->flush();
                $col++;
            }
            if ($i % 3 == 0){
                $vide = '' ;
                for($v = 1 ; $v <= $maxcolonne ; $v++){
                    $vide .= '_';
                }
                $line++;
                $car++;
            }
            $car++;
            $line++;
        }

//        $item1 = new Place();
//        $item1->setNomplace("A1");
//        $item1->setStatutplace("libre");
//        $item1->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle4'));
//        $this->addReference('_reference_AppBundleEntityPlace1', $item1);
//        $manager->persist($item1);

    

    }

}
