<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Reservation;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadFixtureReservation extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Reservation::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Reservation();
        $item1->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle1'));
        $item1->setDatereservation(new \DateTime("2017-09-20 00:00:00"));
        $item1->setHeuredebut(new \DateTime("2017-09-21 16:00:00"));
        $item1->setHeurefin(new \DateTime("2017-09-21 21:00:00"));
        $item1->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item1->setCommentaireclient("test");
        $item1->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item1->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item1->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation1', $item1);
        $manager->persist($item1);

        $item2 = new Reservation();
        $item2->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle1'));
        $item2->setDatereservation(new \DateTime("2017-09-20 00:00:00"));
        $item2->setHeuredebut(new \DateTime("2017-09-20 10:00:00"));
        $item2->setHeurefin(new \DateTime("2017-09-20 11:00:00"));
        $item2->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item2->setCommentaireclient("test");
        $item2->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item2->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item2->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation2', $item2);
        $manager->persist($item2);

        $item3 = new Reservation();
        $item3->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle1'));
        $item3->setDatereservation(new \DateTime("2017-09-20 00:00:00"));
        $item3->setHeuredebut(new \DateTime("2017-09-20 14:30:00"));
        $item3->setHeurefin(new \DateTime("2017-09-20 15:00:00"));
        $item3->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item3->setCommentaireclient("test");
        $item3->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item3->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item3->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation3', $item3);
        $manager->persist($item3);

        $item7 = new Reservation();
        $item7->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle2'));
        $item7->setDatereservation(new \DateTime("2017-09-20 00:00:00"));
        $item7->setHeuredebut(new \DateTime("2017-09-20 14:30:00"));
        $item7->setHeurefin(new \DateTime("2017-09-20 15:00:00"));
        $item7->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item7->setCommentaireclient("test");
        $item7->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item7->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item7->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation7', $item7);
        $manager->persist($item7);

        $item8 = new Reservation();
        $item8->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle2'));
        $item8->setDatereservation(new \DateTime("2017-09-20 00:00:00"));
        $item8->setHeuredebut(new \DateTime("2017-09-20 15:30:00"));
        $item8->setHeurefin(new \DateTime("2017-09-20 16:30:00"));
        $item8->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item8->setCommentaireclient("test");
        $item8->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item8->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item8->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation8', $item8);
        $manager->persist($item8);

        $item9 = new Reservation();
        $item9->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle2'));
        $item9->setDatereservation(new \DateTime("2017-09-20 00:00:00"));
        $item9->setHeuredebut(new \DateTime("2017-09-20 14:30:00"));
        $item9->setHeurefin(new \DateTime("2017-09-20 15:00:00"));
        $item9->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item9->setCommentaireclient("test");
        $item9->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item9->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item9->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation9', $item9);
        $manager->persist($item9);

        $item10 = new Reservation();
        $item10->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle3'));
        $item10->setDatereservation(new \DateTime("2017-09-20 10:00:00"));
        $item10->setHeuredebut(new \DateTime("2017-09-20 09:30:00"));
        $item10->setHeurefin(new \DateTime("2017-09-20 11:30:00"));
        $item10->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item10->setCommentaireclient("test");
        $item10->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item10->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item10->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation10', $item10);
        $manager->persist($item10);

        $item11 = new Reservation();
        $item11->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle3'));
        $item11->setDatereservation(new \DateTime("2017-09-20 20:00:00"));
        $item11->setHeuredebut(new \DateTime("2017-09-20 18:00:00"));
        $item11->setHeurefin(new \DateTime("2017-09-20 19:00:00"));
        $item11->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item11->setCommentaireclient("test");
        $item11->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item11->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item11->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation11', $item11);
        $manager->persist($item11);

        $item12 = new Reservation();
        $item12->setIdsalle($this->getReference('_reference_Proxies__CG__AppBundleEntitySalle3'));
        $item12->setDatereservation(new \DateTime("2017-09-20 20:00:00"));
        $item12->setHeuredebut(new \DateTime("2017-09-21 21:30:00"));
        $item12->setHeurefin(new \DateTime("2017-09-21 22:30:00"));
        $item12->setRemarquereservation("Test de réservation sur la salle 1 pendant une journée
");
        $item12->setCommentaireclient("test");
        $item12->setIdmagasin($this->getReference('_reference_Proxies__CG__AppBundleEntityMagasin1'));
        $item12->setIdmodepaiement($this->getReference('_reference_Proxies__CG__AppBundleEntityModeDePaiement1'));
        $item12->setIdpersonne($this->getReference('_reference_Proxies__CG__AppBundleEntityPersonne8'));
        $this->addReference('_reference_AppBundleEntityReservation12', $item12);
        $manager->persist($item12);

    
        $manager->flush();
    }

}
