easy_admin:
    site_name: '<img alt="GustoCoffee" width="100px" src="/img/gc_logo.png" /> BackOffice'
    design:
        brand_color: rgba(166, 133, 77, 1)
        form_theme:   'vertical'
        color_scheme: 'dark'
        assets:
            favicon: '/img/gc_logo.png'