gc_reservation_page:
    path:    /reservation
    defaults: { _controller: GCReservationBundle:Default:index }

gc_private_page:
    path:    /reservation-private
    defaults: { _controller: GCReservationBundle:Default:private }